# Generated by Django 3.1 on 2020-12-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cartproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
