# Generated by Django 3.1 on 2020-12-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
