# Generated by Django 3.1 on 2020-12-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='count',
            new_name='quantity',
        ),
    ]
